baseURL = 'https://giveexamples.github.io/blog/'
languageCode = 'en-us'
title = '🏠 GiveExamples'
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[params]
[[params.socialIcons]]
name = "github"
url = "https://github.com/giveexamples"